import type { Metadata } from "next";
import { DetailColumns, EditorialCallout } from "@/components/editorial-page";
import { SparkIcon } from "@/components/icons";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { siteUrl } from "@/lib/config";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "About Insightly", description: "A general-interest journal for everyday life, wellbeing, travel, food, blogging, creativity, and more.", alternates: { canonical: `${siteUrl}/about` } };

export default function AboutPage() {
  return <><SiteHeader /><main>
    <section className="about-hero"><div className="container about-hero-inner"><div><span className="eyebrow"><span className="status-dot" /> About the publication</span><h1>Many interests.<br /><em>One curious place.</em></h1></div><div className="about-hero-note"><SparkIcon /><p>Stories for the parts of life that do not fit neatly into one box.</p></div></div></section>
    <section className="container about-body"><div className="about-lede"><span className="about-lede-number">01</span><div><p className="about-lede-large">Insightly is a general-interest journal for people who want to follow their curiosity wherever it leads.</p><p>One day that might mean a gentler morning. The next, a new place, a recipe ritual, a blogging prompt, a creative project, or a question about the technology already in your day.</p></div></div><DetailColumns items={[{ title: "Be curious", body: "We follow questions across categories because a good idea often becomes more interesting when it travels between them." }, { title: "Be useful", body: "We look for clear details, honest context, and small next steps a reader can adapt to their own circumstances." }, { title: "Be human", body: "We make space for lived experience, changing priorities, imperfect attempts, and the joy of learning as we go." }]} /><div className="about-split"><div><span className="eyebrow">What you will find here</span><h2>A wider view of everyday life.</h2></div><div><p>Our journal brings together lifestyle, everyday wellbeing, travel, nature, food, home, blogging, writing, arts, relationships, personal growth, working life, and technology through a human lens.</p><ul><li>Essays that make ordinary moments worth noticing.</li><li>Practical guides for creating, cooking, writing, and exploring.</li><li>Personal perspectives that invite reflection rather than tell you what to think.</li><li>Health and wellbeing pieces clearly framed as general-interest information.</li></ul></div></div><EditorialCallout title="There is always another perspective to discover." href="/blog" label="Browse the journal">Follow a subject you already love, or choose a category you have never explored. The site is designed to let you move naturally from one idea to the next.</EditorialCallout><div className="about-split about-split-last"><div><span className="eyebrow">Our editorial approach</span><h2>Clear, generous, and grounded.</h2></div><div><p>We favour clarity over urgency, context over performance, and practical detail over empty certainty. When a subject depends on personal circumstances, we say so. When a health topic deserves qualified advice, we make that boundary clear.</p><p>This is a demonstration edition. The articles, authors, and photographs are sample content, and the newsletter does not save subscriptions while Firebase is unconfigured.</p></div></div></section>
  </main><SiteFooter /></>;
}
