import type { Metadata } from "next";
import Image from "next/image";
import { DetailColumns, EditorialCallout } from "@/components/editorial-page";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { siteUrl } from "@/lib/config";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "About GeoVaultHQ", description: "Meet GeoVaultHQ: a journal exploring the places, people, and ideas that shape our world.", alternates: { canonical: `${siteUrl}/about` } };

export default function AboutPage() {
  return <><SiteHeader /><main>
    <section className="about-hero"><div className="container about-hero-inner"><div><span className="eyebrow"><span className="status-dot" /> About the publication</span><h1>Many places.<br /><em>One curious world.</em></h1></div><div className="about-hero-note"><Image className="about-hero-logo" src="/geovaulthq-logo.png" alt="GeoVaultHQ globe-and-vault logo" width={160} height={160} sizes="160px" /><p>Stories that bring the world a little closer.</p></div></div></section>
    <section className="container about-body"><div className="about-lede"><span className="about-lede-number">01</span><div><p className="about-lede-large">GeoVaultHQ is a journal for exploring the places, people, and ideas that shape our world.</p><p>From landscapes and local traditions to everyday rituals and the technology connecting us, we follow curiosity wherever it leads.</p></div></div><DetailColumns items={[{ title: "Explore", body: "We follow questions across places and perspectives, because a good idea often becomes more interesting when it travels between them." }, { title: "Understand", body: "We look for clear details, useful context, and small next steps readers can adapt to their own circumstances." }, { title: "Connect", body: "We make space for lived experience and the shared details that help a distant place feel more familiar." }]} /><div className="about-split"><div><span className="eyebrow">What you will find here</span><h2>A wider view of our world.</h2></div><div><p>Our journal brings together travel, nature, food, home, culture, creativity, wellbeing, relationships, working life, and technology through a curious, human lens.</p><ul><li>Stories that make unfamiliar places and ordinary moments worth noticing.</li><li>Practical guides for exploring, creating, cooking, and learning.</li><li>Perspectives that invite reflection rather than tell you what to think.</li><li>Wellbeing pieces clearly framed as general-interest information.</li></ul></div></div><EditorialCallout title="There is always another place or perspective to discover." href="/blog" label="Browse the journal">Follow a subject you already love, or choose one you have never explored. Let each story be a new doorway into the world.</EditorialCallout><div className="about-split about-split-last"><div><span className="eyebrow">Our editorial approach</span><h2>Curious, clear, and grounded.</h2></div><div><p>We favour clarity over urgency, context over performance, and practical detail over empty certainty. When a subject depends on personal circumstances, we say so. When a health topic deserves qualified advice, we make that boundary clear.</p><p>This is a demonstration edition. The articles, authors, and photographs are sample content, and the newsletter does not save subscriptions while Firebase is unconfigured.</p></div></div></section>
  </main><SiteFooter /></>;
}
