import { NextResponse } from "next/server";
import { Timestamp } from "firebase-admin/firestore";
import { getAdminDb } from "@/lib/firebase/admin";
import { getAdminSession } from "@/lib/admin-session";
import { postUpdateSchema } from "@/lib/post-schema";
import { resolvePublicationDate } from "@/lib/publishing";

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { const session = await getAdminSession(); const db = getAdminDb(); if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (!db) return NextResponse.json({ error: "Firebase is not configured" }, { status: 503 }); const id = (await params).id; const parsed = postUpdateSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid post data", details: parsed.error.flatten() }, { status: 400 }); const body = parsed.data; const current = await db.collection("posts").doc(id).get(); if (!current.exists) return NextResponse.json({ error: "Post not found" }, { status: 404 }); const currentData = current.data() ?? {}; if (body.authorId || body.categoryId || body.tagIds) { const [author, category, tags] = await Promise.all([db.collection("authors").doc(body.authorId ?? String(currentData.authorId)).get(), db.collection("categories").doc(body.categoryId ?? String(currentData.categoryId)).get(), Promise.all((body.tagIds ?? (Array.isArray(currentData.tagIds) ? currentData.tagIds : [])).map((tagId) => db.collection("tags").doc(tagId).get()))]); if (!author.exists || !category.exists || tags.some((tag) => !tag.exists)) return NextResponse.json({ error: "Choose existing author, category and tag records." }, { status: 400 }); } if (typeof body.slug === "string" && body.slug !== currentData.slug) { const duplicate = await db.collection("posts").where("slug", "==", body.slug).limit(2).get(); if (duplicate.docs.some((doc) => doc.id !== id)) return NextResponse.json({ error: "That slug is already in use." }, { status: 409 }); }
  const currentPublishedAt = current.data()?.publishedAt && typeof current.data()?.publishedAt.toDate === "function" ? current.data()?.publishedAt.toDate() : new Date(current.data()?.publishedAt ?? ""); const publishedAt = typeof body.publishedAt === "string" ? new Date(body.publishedAt) : null; if (publishedAt && Number.isNaN(publishedAt.getTime())) return NextResponse.json({ error: "Invalid publish date." }, { status: 400 }); const effectivePublishedAt = publishedAt ?? currentPublishedAt; if (body.status === "scheduled" && (Number.isNaN(effectivePublishedAt.getTime()) || effectivePublishedAt.getTime() <= Date.now())) return NextResponse.json({ error: "Scheduled posts must have a future publish date." }, { status: 400 }); const updates = { ...body, updatedAt: Timestamp.now() } as Record<string, unknown>; if (body.status === "published") updates.publishedAt = Timestamp.fromDate(resolvePublicationDate("published", effectivePublishedAt)); else if (publishedAt) updates.publishedAt = Timestamp.fromDate(publishedAt); if (typeof body.content === "string") updates.readingTime = Math.max(1, Math.ceil(body.content.replace(/<[^>]+>/g, " ").split(/\s+/).length / 200)); if (typeof body.slug === "string" && body.slug !== current.data()?.slug) await db.collection("redirects").doc(String(current.data()?.slug)).set({ from: current.data()?.slug, to: body.slug, createdAt: Timestamp.now() }); await db.collection("posts").doc(id).update(updates); return NextResponse.json({ ok: true }); }
export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) { const session = await getAdminSession(); const db = getAdminDb(); if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (!db) return NextResponse.json({ error: "Firebase is not configured" }, { status: 503 }); const ref = db.collection("posts").doc((await params).id); if (!(await ref.get()).exists) return NextResponse.json({ error: "Post not found" }, { status: 404 }); await ref.delete(); return NextResponse.json({ ok: true }); }
