import Link from "next/link";
import Image from "next/image";
import type { PostWithRelations } from "@/lib/types";
import { formatDate } from "@/lib/utils";
import { ArticleCard } from "./article-card";
import { NewsletterForm } from "./newsletter-form";
import { ArrowIcon, SparkIcon } from "./icons";

export function HomeSections({ posts, categories }: { posts: PostWithRelations[]; categories: Array<{ name: string; slug: string; description?: string }> }) {
  const hero = posts[0];
  const latest = posts.slice(1, 5);
  const trending = [...posts].sort((a, b) => b.viewCount - a.viewCount).slice(0, 4);
  const picks = posts.filter((post) => !latest.includes(post) && post !== hero).slice(0, 3);
  const spotlightStories = posts.filter((post) => post.category.slug === "health-wellness");
  const spotlight = spotlightStories.find((post) => post !== hero) ?? spotlightStories[0];
  const guides = posts.filter((post) => post.tags.some((tag) => tag.slug === "how-to")).slice(0, 3);
  const authors = [...new Map(posts.map((post) => [post.author.id, post.author])).values()].slice(0, 4);

  return <>
    {hero && <section className="featured-section" id="home-banner" aria-label="Featured story">
      <article className="cover-story">
        <Image src={hero.featuredImage.url} alt={hero.featuredImage.alt} fill preload sizes="100vw" />
        <div className="cover-topline container"><span className="story-badge"><SparkIcon width="13" height="13" /> The cover story</span><span>Fresh perspectives / {new Date(hero.publishedAt).getUTCFullYear()}</span></div>
        <div className="cover-content container"><Link className="eyebrow" href={`/category/${hero.category.slug}`}>{hero.category.name}</Link><h2><Link className="cover-story-link" href={`/blog/${hero.slug}`}>{hero.title}</Link></h2><p>{hero.excerpt}</p><div className="cover-bottom"><div className="story-author"><Image src={hero.author.avatarUrl} alt="" width={36} height={36} /><span>{hero.author.name}<small>{formatDate(hero.publishedAt)} · {hero.readingTime} min read</small></span></div><span className="cover-read" aria-hidden="true">Read the story <span className="round-arrow"><ArrowIcon /></span></span></div></div>
      </article>
    </section>}

    <section className="publication-intro container" aria-labelledby="publication-title">
      <div><span className="eyebrow publication-kicker"><span className="status-dot" /> A journal for curious minds</span><h1 id="publication-title">Stories for <em>every side of life.</em><SparkIcon className="title-spark" /></h1></div>
      <p>Live well. Go somewhere new.<br className="desktop-break" /> Find something that speaks to you.</p>
    </section>

    <nav className="interest-nav container" aria-label="Explore interests">{categories.slice(0, 6).map((category) => <Link key={category.slug} href={`/category/${category.slug}`}>{category.name}</Link>)}<Link className="all-interests" href="/topics">All topics <ArrowIcon width="14" height="14" /></Link></nav>

    {trending.length > 0 && <section data-home-section="1" className="trending-section container" aria-labelledby="trending-title"><div className="trending-heading"><span className="status-dot" /><h2 id="trending-title">On the radar</h2><span>What’s catching attention</span></div><div className="trending-grid">{trending.map((post, index) => <article key={post.id}><span className="trending-number">0{index + 1}</span><div><Link className="eyebrow" href={`/category/${post.category.slug}`}>{post.category.name}</Link><h3><Link href={`/blog/${post.slug}`}>{post.title}</Link></h3></div></article>)}</div></section>}

    <section data-home-section="2" className="section latest-section container" aria-labelledby="latest-title"><div className="section-heading"><div><span className="eyebrow section-index">01 / The journal</span><h2 id="latest-title">Latest articles<span className="heading-dot">.</span></h2></div><Link href="/blog" className="text-link">View the journal <ArrowIcon /></Link></div><div className="journal-layout"><div className="latest-grid">{latest.map((post) => <ArticleCard key={post.id} post={post} />)}</div><aside className="editors-sidebar" aria-labelledby="editors-title"><div className="editors-sidebar-heading"><SparkIcon width="24" height="24" /><h2 id="editors-title">The editor’s edit</h2></div><p className="editors-sidebar-intro">A few stories we’re still thinking about.</p><div className="reading-list">{picks.map((post, index) => <article key={post.id}><span className="reading-number">0{index + 1}</span><div><Link className="eyebrow" href={`/category/${post.category.slug}`}>{post.category.name}</Link><h3><Link href={`/blog/${post.slug}`}>{post.title}</Link></h3><span className="reading-meta">{post.author.name} · {post.readingTime} min</span></div></article>)}</div><div className="perspective-note"><SparkIcon width="44" height="44" /><p>Big ideas.<br />Human perspectives.<br /><em>Always curious.</em></p><Link href="/about" className="text-link">Meet the publication <ArrowIcon width="16" /></Link></div></aside></div><div className="section-bottom"><span>Your next favorite story is one click away.</span><Link href="/blog" className="button button-light">Explore all stories <ArrowIcon /></Link></div></section>

    {spotlight && <section data-home-section="3" className="spotlight-section" aria-labelledby="spotlight-title"><div className="container"><div className="section-heading"><div><span className="eyebrow section-index">02 / In focus</span><h2 id="spotlight-title">A little more <em>wellbeing.</em></h2></div><Link href="/category/health-wellness" className="text-link">Explore health & wellness <ArrowIcon /></Link></div><div className="spotlight-layout"><Link href={`/blog/${spotlight.slug}`} className="spotlight-image"><Image src={spotlight.featuredImage.url} alt={spotlight.featuredImage.alt} fill sizes="(max-width: 760px) 100vw, 600px" /><span className="spotlight-image-caption">A little space for everyday wellbeing <ArrowIcon /></span></Link><div className="spotlight-copy"><span className="eyebrow">Everyday wellbeing</span><h3><Link href={`/blog/${spotlight.slug}`}>{spotlight.title}</Link></h3><p>{spotlight.excerpt}</p><Link href={`/blog/${spotlight.slug}`} className="button spotlight-button">Get the full perspective <ArrowIcon /></Link><div className="spotlight-related">{spotlightStories.filter((post) => post !== spotlight).slice(0, 2).map((post) => <Link key={post.id} href={`/blog/${post.slug}`}><span><small>Keep exploring</small>{post.title}</span><ArrowIcon /></Link>)}</div></div></div></div></section>}

    <section data-home-section="4" className="section categories-section container" id="topics" aria-labelledby="categories-title"><div className="section-heading"><div><span className="eyebrow section-index">03 / Follow your curiosity</span><h2 id="categories-title">Find your next rabbit hole<span className="heading-dot">.</span></h2></div><p className="section-note">Go deep on what you love.<br />Get curious about something new.</p></div><div className="category-grid">{categories.map((category, index) => <Link key={category.slug} href={`/category/${category.slug}`} className="category-tile"><span className="category-number">{String(index + 1).padStart(2, "0")}</span><span className="category-name">{category.name}</span><small>{category.description}</small><ArrowIcon /></Link>)}</div></section>

    {guides.length > 0 && <section data-home-section="5" className="guides-section container" aria-labelledby="guides-title"><div className="guides-intro"><span className="eyebrow section-index">04 / From knowing to doing</span><h2 id="guides-title">Less theory.<br /><em>More possibility.</em></h2><p>Practical ideas for cooking, creating, writing, and making everyday life a little more your own.</p><Link href="/tag/how-to" className="button button-dark">Find your next how-to <ArrowIcon /></Link><div className="guide-art" aria-hidden="true"><span /><span /><span /><SparkIcon /></div></div><div className="guide-list">{guides.map((post, index) => <article key={post.id}><div className="guide-content"><span className="eyebrow">Field guide / 0{index + 1}</span><h3><Link href={`/blog/${post.slug}`}>{post.title}</Link></h3><span className="reading-meta">{post.category.name} · {post.readingTime} min read</span></div><Link href={`/blog/${post.slug}`} className="guide-image"><Image src={post.featuredImage.url} alt={post.featuredImage.alt} fill sizes="(max-width: 480px) 90px, 145px" /><span><ArrowIcon width="15" height="15" /></span></Link></article>)}</div></section>}

    {authors.length > 0 && <section data-home-section="6" className="section writers-section container" aria-labelledby="writers-title"><div className="section-heading"><div><span className="eyebrow section-index">05 / People, not just bylines</span><h2 id="writers-title">Voices with a point of view<span className="heading-dot">.</span></h2></div><Link href="/about" className="text-link">Our story <ArrowIcon /></Link></div><div className="writers-grid">{authors.map((author) => <article className="writer-card" key={author.id}><div className="writer-top"><Link href={`/author/${author.slug}`}><Image src={author.avatarUrl} alt={author.name} width={72} height={72} /></Link><ArrowIcon /></div><h3><Link href={`/author/${author.slug}`}>{author.name}</Link></h3><p>{author.bio}</p><Link className="writer-link" href={`/author/${author.slug}`}>Read their stories <ArrowIcon width="14" height="14" /></Link></article>)}</div></section>}

    <section data-home-section="7" className="newsletter-section container" id="newsletter" aria-labelledby="newsletter-title"><div className="newsletter-decoration" aria-hidden="true"><SparkIcon /><span className="orbit orbit-one" /><span className="orbit orbit-two" /></div><div className="newsletter-inner"><div><span className="eyebrow">06 / The weekly perspective</span><h2 id="newsletter-title">Good reads.<br /><em>Straight to your inbox.</em></h2><p>A thoughtful edit of our best stories. A little inspiration.<br className="desktop-break" /> Something worth opening.</p></div><div className="newsletter-signup"><span className="newsletter-label">Make room for a fresh perspective.</span><NewsletterForm /><p className="newsletter-promise">Free to join. Unsubscribe whenever you like.</p></div></div></section>
  </>;
}
