import type { Metadata } from "next";
import Link from "next/link";
import { ArticleCard } from "@/components/article-card";
import { SearchForm } from "@/components/search-form";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { getCategories, getPosts, getSiteSettings } from "@/lib/data";
import { siteUrl } from "@/lib/config";

export const dynamic = "force-dynamic";

export async function generateMetadata(): Promise<Metadata> { const settings = await getSiteSettings(); return { title: "Latest articles", description: `Practical guides and ideas from ${settings.siteName}.`, alternates: { canonical: `${siteUrl}/blog` } }; }

export default async function BlogPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const page = Number(params.page ?? 1) || 1; const cursor = typeof params.cursor === "string" ? params.cursor : undefined; const sort = params.sort === "oldest" || params.sort === "popular" ? params.sort : "newest"; const category = typeof params.category === "string" ? params.category : undefined; const [{ posts, total, nextCursor }, categories] = await Promise.all([getPosts({ page: cursor ? undefined : page, cursor, pageSize: 9, sort, categorySlug: category }), getCategories()]); const pages = Math.ceil(total / 9);
  const nextHref = nextCursor ? `/blog?cursor=${encodeURIComponent(nextCursor)}${category ? `&category=${category}` : ""}${sort !== "newest" ? `&sort=${sort}` : ""}` : null;
  return <><SiteHeader /><main><section className="page-hero"><div className="container"><span className="eyebrow">The GeoVaultHQ journal</span><h1>Ideas worth carrying forward.</h1><p>Explore stories about places, people, and ideas that open up a wider view of the world.</p><SearchForm /></div></section><section className="section container"><div className="listing-note"><article><h3>Read widely</h3><p>Move between subjects and let one story lead naturally to another.</p></article><article><h3>Save a question</h3><p>Every article begins with something worth noticing, trying, or discussing.</p></article><article><h3>Take what fits</h3><p>Use practical ideas as invitations, and adapt them to your own life.</p></article></div><div className="filters"><Link className={!category ? "filter-pill active" : "filter-pill"} href="/blog">All articles</Link>{categories.map((item) => <Link key={item.slug} className={category === item.slug ? "filter-pill active" : "filter-pill"} href={`/blog?category=${item.slug}`}>{item.name}</Link>)}</div><div className="section-heading"><div><span className="eyebrow">{total} stories</span><h2>Latest articles</h2></div><div className="filters"><Link className={sort === "newest" ? "filter-pill active" : "filter-pill"} href={`/blog?${category ? `category=${category}&` : ""}sort=newest`}>Newest</Link><Link className={sort === "oldest" ? "filter-pill active" : "filter-pill"} href={`/blog?${category ? `category=${category}&` : ""}sort=oldest`}>Oldest</Link><Link className={sort === "popular" ? "filter-pill active" : "filter-pill"} href={`/blog?${category ? `category=${category}&` : ""}sort=popular`}>Popular</Link></div></div>{posts.length ? <div className="article-grid">{posts.map((post) => <ArticleCard key={post.id} post={post} />)}</div> : <div className="admin-card"><h2>No articles found</h2><p>Try a different category or search term.</p></div>}{pages > 1 && !cursor && <div className="pagination">{Array.from({ length: pages }, (_, index) => index + 1).map((item) => <Link key={item} className={item === page ? "active" : ""} href={`/blog?page=${item}${category ? `&category=${category}` : ""}${sort !== "newest" ? `&sort=${sort}` : ""}`}>{item}</Link>)}</div>}{nextHref && <div className="load-more"><Link className="button button-light" href={nextHref}>Load more articles ↗</Link></div>}</section></main><SiteFooter /></>;
}
